02:makeNewFile(() !; быстро засоряется. поменьше файлов создать?

diff --git a/src/02/makeFilesFolders b/src/02/makeFilesFolders
--- a/src/02/makeFilesFolders
+++ b/src/02/makeFilesFolders
@@ -77,63 +77,6 @@ create_newfile()
   fi
 }
 
-create_newfolder()
-{
-	new_dName=$(generate $d_letters)
-	local tmp_dName=$(echo ${new_dName})
-	new_dName=${new_dName}_${add_date}
-	local len_new_dName=${#new_dName}
-        full_dName=$(echo "${abs_way}/${new_dName}")	
-	
-	while true
-	do
-	  if [[ ${len_new_dName} -gt 255 ]]; then
-	      echo "folder_length_is_gt_255_characters"; return
-	  fi
-
-	  if [[ ! -d ${full_dName} ]]; then
-	    break 1
-	  fi
-	
-	  local len=${#tmp_dName}
-	  local lastElem=${tmp_dName:$len-1:1}
-	  local firstElem=${tmp_dName:0:1}
-	  local let "random=$RANDOM % 2"
-	  if [[ $random -eq 0 ]]; then
-	      new_dName=${firstElem}${tmp_dName}
-	  else
-	      new_dName=${tmp_dName}${lastElem}
-	  fi
-	  tmp_dName=${new_dName}
-	  new_dName=${new_dName}_${add_date}
-	  full_dName=$(echo "${abs_way}/${new_dName}")
-	  let "len_new_dName=$len_new_dName + 1"
-	done
-
-	mkdir -p ${full_dName} 2>/dev/null
-	#Если такая директория существует, то выдается сообщение о
-	#создании. Прерывается процесс. А с флагом "-p"
-	#не останавливается процесс, но и папка не создаётся.
-	#Выше в цикле создается уникальное имя для папки. 
-	#Поэтому флаг -p просто для знания такой опции.
-	#вывод ошибок перенаправляю в /dev/null, чтобы не показывались
-	#сообщения о запрете доступа. Т.к. это из-за sudo. Sudo делаю дальше.
-
-	if [ $? -ne 0 ] ; then
-	  sudo mkdir -p ${full_dName}
-	  if [ $? -ne 0 ] ; then
-	    echo "Error when creating folder" ; exit 1
-	  fi
-	fi
-
-	echo "${full_dName}; ${dateLog}" >> $logfile
-	if [ $? -ne 0 ] ; then
-	  sudo echo "${full_dName}; ${dateLog}" >> $logfile 
-	  if [ $? -ne 0 ] ; then
-	    echo "Error when updating logfile" ; exit 1
-	  fi
-	fi
-}
 
 makeNewFolder()
 {
@@ -181,5 +124,36 @@ makeNewFolder()
 
 makeNewFile()
 {
-    local dasd=1
+    new_fName=$(generate $letters_f_name)
+    newfExt=$(generate $letters_f_ext)
+    newFile=${new_fName}_${add_date}.${newfExt}
+    len_newFile=${#newFile}
+    full_fName=$(echo "$element/${new_dName}/${newFile}")
+
+  while true
+  do
+      if [[ ${len_newFile} -gt 255 ]]; then
+        full_fName=$(echo "${element}/${new_dName}/_${add_date}")
+        echo "File_length_is_gt_255_characters"
+        break 1
+      fi
+
+      if [[ ! -f ${full_fName} ]]; then
+        break 1
+      fi
+
+      local len=${#full_fName}
+      local lastSymbol=${full_fName:${len}-1:1}
+      full_fName=${full_fName}${lastSymbol}
+      let "len_newFile=$len_newFile + 1"
+  done
+
+  sudo fallocate -l ${file_size}K ${full_fName} 2>/dev/null
+  if [[ $? -ne 0 ]]
+      then echo "Error when creating file"; exit 1
+  fi
+  sudo echo "${full_fName}; ${dateLog}; ${file_size}Mb" >> $logfile
+  if [ $? -ne 0 ] ; then
+      echo "Error when updating logfile" ; exit 1
+  fi
 }
